// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package goods

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// StreamGreeterClient is the client API for StreamGreeter service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type StreamGreeterClient interface {
	GoodsCreated(ctx context.Context, in *CreateGoodsReq, opts ...grpc.CallOption) (*GoodsResp, error)
	CreateSku(ctx context.Context, in *CreateSkuReq, opts ...grpc.CallOption) (*CreateSkuRes, error)
}

type streamGreeterClient struct {
	cc grpc.ClientConnInterface
}

func NewStreamGreeterClient(cc grpc.ClientConnInterface) StreamGreeterClient {
	return &streamGreeterClient{cc}
}

func (c *streamGreeterClient) GoodsCreated(ctx context.Context, in *CreateGoodsReq, opts ...grpc.CallOption) (*GoodsResp, error) {
	out := new(GoodsResp)
	err := c.cc.Invoke(ctx, "/goods.StreamGreeter/GoodsCreated", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *streamGreeterClient) CreateSku(ctx context.Context, in *CreateSkuReq, opts ...grpc.CallOption) (*CreateSkuRes, error) {
	out := new(CreateSkuRes)
	err := c.cc.Invoke(ctx, "/goods.StreamGreeter/CreateSku", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// StreamGreeterServer is the server API for StreamGreeter service.
// All implementations must embed UnimplementedStreamGreeterServer
// for forward compatibility
type StreamGreeterServer interface {
	GoodsCreated(context.Context, *CreateGoodsReq) (*GoodsResp, error)
	CreateSku(context.Context, *CreateSkuReq) (*CreateSkuRes, error)
	mustEmbedUnimplementedStreamGreeterServer()
}

// UnimplementedStreamGreeterServer must be embedded to have forward compatible implementations.
type UnimplementedStreamGreeterServer struct {
}

func (UnimplementedStreamGreeterServer) GoodsCreated(context.Context, *CreateGoodsReq) (*GoodsResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GoodsCreated not implemented")
}
func (UnimplementedStreamGreeterServer) CreateSku(context.Context, *CreateSkuReq) (*CreateSkuRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateSku not implemented")
}
func (UnimplementedStreamGreeterServer) mustEmbedUnimplementedStreamGreeterServer() {}

// UnsafeStreamGreeterServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to StreamGreeterServer will
// result in compilation errors.
type UnsafeStreamGreeterServer interface {
	mustEmbedUnimplementedStreamGreeterServer()
}

func RegisterStreamGreeterServer(s grpc.ServiceRegistrar, srv StreamGreeterServer) {
	s.RegisterService(&StreamGreeter_ServiceDesc, srv)
}

func _StreamGreeter_GoodsCreated_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateGoodsReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StreamGreeterServer).GoodsCreated(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/goods.StreamGreeter/GoodsCreated",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StreamGreeterServer).GoodsCreated(ctx, req.(*CreateGoodsReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _StreamGreeter_CreateSku_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateSkuReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StreamGreeterServer).CreateSku(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/goods.StreamGreeter/CreateSku",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StreamGreeterServer).CreateSku(ctx, req.(*CreateSkuReq))
	}
	return interceptor(ctx, in, info, handler)
}

// StreamGreeter_ServiceDesc is the grpc.ServiceDesc for StreamGreeter service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var StreamGreeter_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "goods.StreamGreeter",
	HandlerType: (*StreamGreeterServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GoodsCreated",
			Handler:    _StreamGreeter_GoodsCreated_Handler,
		},
		{
			MethodName: "CreateSku",
			Handler:    _StreamGreeter_CreateSku_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "goods.proto",
}
